from paperless_ai_tagger.processor import (
    ProcessingStats,
    _is_autogenerated_title,
    _summarize_changes,
)


class TestIsAutogeneratedTitle:
    """Tests for _is_autogenerated_title detection."""

    # Existing behavior: file extensions and scanner prefixes
    def test_scan_underscore_pdf(self):
        assert _is_autogenerated_title("scan_20240115.pdf") is True

    def test_img_prefix(self):
        assert _is_autogenerated_title("IMG_4521.jpg") is True

    def test_tiff_extension(self):
        assert _is_autogenerated_title("document.tiff") is True

    def test_empty_title(self):
        assert _is_autogenerated_title("") is True

    def test_real_title_tax_return(self):
        assert _is_autogenerated_title("2024 Tax Return") is False

    def test_real_title_invoice(self):
        assert _is_autogenerated_title("Invoice from Acme") is False

    # New: "Scan " with space (Paperless-normalized titles)
    def test_scan_space_with_date(self):
        assert _is_autogenerated_title("Scan 2026-03-30 07.29.09") is True

    def test_scan_space_simple(self):
        assert _is_autogenerated_title("Scan 001") is True

    # New: original_file_name matching
    def test_title_matches_filename_without_extension(self):
        assert (
            _is_autogenerated_title(
                "Scan 2026-03-30 07.29.09",
                original_file_name="Scan 2026-03-30 07-29-09.pdf",
            )
            is True
        )

    def test_title_matches_filename_with_extension(self):
        assert (
            _is_autogenerated_title(
                "scan_20240115.pdf",
                original_file_name="scan_20240115.pdf",
            )
            is True
        )

    def test_title_matches_filename_exact_no_ext(self):
        assert (
            _is_autogenerated_title(
                "my-scanned-doc",
                original_file_name="my-scanned-doc.pdf",
            )
            is True
        )

    def test_title_does_not_match_filename_uses_pattern_fallback(self):
        # Title doesn't match filename AND doesn't match patterns -> False
        assert (
            _is_autogenerated_title(
                "My Custom Title",
                original_file_name="scan_20240115.pdf",
            )
            is False
        )

    def test_filename_comparison_case_insensitive(self):
        assert (
            _is_autogenerated_title(
                "RECEIPT 2024",
                original_file_name="Receipt 2024.pdf",
            )
            is True
        )

    def test_filename_separator_normalization(self):
        # Paperless may normalize dashes to dots or vice versa
        assert (
            _is_autogenerated_title(
                "doc-2024-01-15",
                original_file_name="doc.2024.01.15.pdf",
            )
            is True
        )

    # New: generic titles
    def test_document_generic(self):
        assert _is_autogenerated_title("document") is True

    def test_untitled_generic(self):
        assert _is_autogenerated_title("untitled") is True

    def test_attachment_generic(self):
        assert _is_autogenerated_title("Attachment") is True

    def test_download_generic(self):
        assert _is_autogenerated_title("Download") is True

    # Ensure real titles with generic words embedded are NOT flagged
    def test_real_title_containing_document_word(self):
        assert _is_autogenerated_title("Important Document from Bank") is False

    def test_real_title_my_custom(self):
        assert _is_autogenerated_title("My Custom Title") is False

    def test_no_original_filename(self):
        # Without original_file_name, only patterns are checked
        assert _is_autogenerated_title("random-file-name-2024") is False


def test_summarize_changes():
    payload = {"title": "New Title", "correspondent": 5, "document_type": 3}
    tag_ids = [1, 2, 99]
    result = _summarize_changes(payload, tag_ids, 99)
    assert "title changed" in result
    assert "2 tags set" in result
    assert "correspondent set" in result
    assert "type set" in result
    assert "marked as processed" in result


def test_summarize_changes_tags_only():
    payload = {"tags": [1, 2, 99]}
    result = _summarize_changes(payload, [1, 2, 99], 99)
    assert "2 tags set" in result
    assert "title" not in result


def test_processing_stats_init():
    stats = ProcessingStats()
    assert stats.processed == 0
    assert stats.skipped == 0
    assert stats.failed == 0
    assert stats.tags_created == 0
