from paperless_ai_tagger.processor import (
    ProcessingStats,
    _is_autogenerated_title,
    _summarize_changes,
)


def test_is_autogenerated_title():
    assert _is_autogenerated_title("scan_20240115.pdf") is True
    assert _is_autogenerated_title("IMG_4521.jpg") is True
    assert _is_autogenerated_title("document.tiff") is True
    assert _is_autogenerated_title("") is True
    assert _is_autogenerated_title("2024 Tax Return") is False
    assert _is_autogenerated_title("Invoice from Acme") is False


def test_summarize_changes():
    payload = {"title": "New Title", "correspondent": 5, "document_type": 3}
    tag_ids = [1, 2, 99]
    result = _summarize_changes(payload, tag_ids, 99)
    assert "title changed" in result
    assert "2 tags set" in result
    assert "correspondent set" in result
    assert "type set" in result
    assert "marked as processed" in result


def test_summarize_changes_tags_only():
    payload = {"tags": [1, 2, 99]}
    result = _summarize_changes(payload, [1, 2, 99], 99)
    assert "2 tags set" in result
    assert "title" not in result


def test_processing_stats_init():
    stats = ProcessingStats()
    assert stats.processed == 0
    assert stats.skipped == 0
    assert stats.failed == 0
    assert stats.tags_created == 0
